a = int(input("Ingrese un numero entero"))
b = int(input("Ingrese un numero entero"))
c = int(input("Ingrese un numero entero"))
print("Usted ingresa los valores:", a, b, c)
print(a, "es mayor que", b, )
print(a, "y", b, "son iguales", )
print(a, "es el mayor de todos", )
print(b, "es el menor de todos", )
print(a, "es mayor que alguno de los otros dos", )
print(a, "es menor o igual que alguno de los otros dos", )
print("Los tres numeros son iguales", )
print("Los tres numeros son distintos", )
print(a, "es par", )
print("alguno es par", )
print("ninguno es par", )
print("todos son pares", )
print(a, "es multiplo de 3", )
print(a, "es multiplo de 3 y de 5",)
print(a, "es multiplo de 3 y par", )
print(a, "-", b, "da un numero positivo", )
print(a, "-", b, "da un numero par positivo", )